### PR TITLE
Meganav update for Web Standards

### PR DESCRIPTION
**Pull request by nathan-rollins**
Adjusted colors of mega menu divider and menu dropdown caret. Also added fix for focused menu items not stretching background color to L-R edges of container.

Dropdown menu items that were current focus or hovered had small gaps in the background color highlighting. It derives from the way we structure the css of the meganav on top of bootstrap, and how the bootstrap column padding is then inherited downward. I'm not thrilled with this particular solution, which involves some negative margins to push that background to the edge. This also requires a compensating increase in the padding values for the menu text.

### CODE REVIEW

**Comment by rraub** [comment]
The Caret color doesn't seem to match the text on hover:
screen shot 2016-06-03 at 1 48 55 pm
 or activation:
screen shot 2016-06-03 at 1 52 02 pm

Webspark version: 
screen shot 2016-06-03 at 1 51 18 pm

**Comment by nathan-rollins** [comment]
No, it doesn't. This is what the Web Standards now call for. It has grown on me and I decided to keep it in, but if you would prefer it out, I can do that.

**Comment by rraub** [comment]
Wow I didn't notice that the standards actually defined that, 

Screenshot for reference:screen shot 2016-06-03 at 2 05 44 pm

Notice they don't define a color for the carrot on activate/selected. I would take that to mean it matches the text?? I guess I can ask around on slack to see if anyone else has an idea if this is a error in the documentation or the implementation. Good Catch!

**Comment by nathan-rollins** [comment]
Good point. That would be my interpretation too, active/selected would have the caret match text color (gold).

**Comment by rraub** [comment]
The hover state is the only time that it looks odd to me, I actually kind of like how its muted when not active, selected or hovered.

**Comment by rraub** [comment]
Could you add carrots into the Navbar documentation that shows the different states since the carrots might not match the text? https://gios-asu.github.io/ASU-Web-Standards-Bootstrap/section-navigation.html#kssref-navigation-web-standards

**Comment by rraub** [comment]
Also while I'm thinking about it, could you see if travis will pass the wraith tests on this branch now that you got it working again?

**Comment by rraub** [comment]
Lets merge this in and if we hear back that the standards for the carrot colors is different then we will change it. But for now its not worth waiting on them

**Pull request merged**
