### PR TITLE
Accessibility Update, Version 0.4.0

### LINKED ISSUE #151: Do not use pixel values for font size
Use ems and rems. Use 1rem at the root.

Check buttons too.

### LINKED ISSUE #153: Refrain from using the line-height-computed
https://github.com/gios-asu/ASU-Web-Standards-Bootstrap/blob/develop/scss/variables/_typography.scss#L31

### PR DESCRIPTION
**Pull request by idmontie**
Overall re-haul of how font sizes and line heights are calculated. Everything now uses rems, instead of pixel values.

Close #151 
Close #153

### CODE REVIEW

**Comment by idmontie** [comment]
I have visually inspected this with the old theme. We should get Wraith set up eventually.

**Comment by idmontie** [comment]
Before:

image


After

image

**Comment by idmontie** [comment]
Here is the diff:

image

**Comment by idmontie** [comment]
The diff is the result of trying to get rid of that extra white bar that came from the innovation badge. It looks like I didn't move it perfectly.

**Comment by idmontie** [comment]
Alright, here is the latest diff:

image

**Comment by rraub** [comment]
That white bar at the bottom has bugged me for a while, glad to see that gone.  Did you look at a mega navigation menu for your tests?

**Comment by idmontie** [comment]
@rraub Only briefly since it's hard to diff. Nothing seemed borked on my VM. Let me post a picture:

image

**Comment by rraub** [comment]
The triple home button seems like only glaring problem :smile: 

It might be worth spending a minute to see if we can remove px font-size values in the scss linter [example](https://github.com/lonelyplanet/rizzo-next/blob/master/.scss-lint.yml#L194).

**Comment by idmontie** [comment]
@rraub We can enforce it, but there are a few places where I left font sizes as pixels since they were used for iconography for things like external links - namely places where actual text is not used.

Maybe next version?

**Comment by idmontie** [comment]
Meh, bit the bullet and just made the change.

**Comment by rraub** [comment]
@idmontie i was about to just make an issue to remind us to do that later. If that lint works out well for us we can add it to some of our other repos to keep us honest.

**Pull request merged**
