### PR TITLE
Update build setup

### PR DESCRIPTION
**Pull request by nathan-rollins**
Added .editorconfig settings file to auto-configure editors to use spaces, remove trailing spaces, etc.

Also, I am moving the vendor.js scripts over to the WordPress theme. This will allow bower and grunt to manage all version updates and building in one locations with the other dependencies.

### CODE REVIEW

**Comment by nathan-rollins** [comment]
Also, see incoming PR on ASU-Web-Standards-Wordpress-Theme for the other half of this updated build process.

**Comment by nathan-rollins** [comment]
Ugh, Ok. So moving those dependencies to the WordPress theme breaks our tests. I need to rethink what I am doing here.

**Comment by rraub** [comment]
We need these vendor files as part of the ASU Web Standards, more than just the WordPress theme will need them. So because of that they need to stay here, now there is totally room for improvement considering they are right now just all statically put together in one file.

**Comment by rraub** [comment]
your editor config stuff should probably get merged in if you want to seperate that out into another PR 👍

**Pull request closed without merging**
