### PR TITLE
Update styling for events/news paginator

### PR DESCRIPTION
**Pull request by nathan-rollins**
This is the theme update for the [GIOS API PR 428](https://github.com/gios-asu/gios2-php/pull/428).

### CODE REVIEW

**Comment by nathan-rollins** [comment]
Preview of the paginator:
screen shot 2016-11-17 at 10 57 56 am

**Comment by rraub** [comment]
Could you put these two examples of the paginator into the docs? That would be a good place to see it in a working demo with code.

**Comment by nathan-rollins** [comment]
There, that should do it. I kept the script code in the example, since including the code inline during server-side construction of the html is easier right now for passing the base url into the script.

**Comment by rraub** [comment]
I forget the reason for using `#/` rather than just `#` in the href attributes, why was that again?

**Comment by nathan-rollins** [comment]
#/ ensures clicking on the link doesn't jump to the top of the page. You can do the same thing using other anchor strings, but it looks like #/ is somewhat the accepted standard for this particular case.

**Pull request merged**
